spring:
  application:
    name: image

wasabi:
  access-key: PX088GGZ038MS0WKFKY6
  secret-key: kva4aCngUSUhq4qo5hmGA5VWeYqn1VRgk6Y2NqrT
  region: us-east-1
  endpoint: https://s3.wasabisys.com
  bucket-name: certeiro
